services:
  main-backend:
    build:
      dockerfile: Dockerfile
    container_name: web-backend
    ports:
      - "8001:8001"
    command: "uvicorn application.api.main:app --reload --host 0.0.0.0 --port 8001"
    env_file:
      - .env